use_frameworks!

platform :ios, '9.0'

target 'HCButtonGenerator_Example' do
  pod 'HCButtonGenerator', :path => '../'

  target 'HCButtonGenerator_Tests' do
    inherit! :search_paths

    
  end
end
